### ISSUE TITLE
bad indentation of a mapping within configuration.yaml

### ISSUE THREAD

**Issue by AndreB81** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#10]
Cheers, 
while adding the config parameter into configuration.yaml. It states that something like "bad indentation of a mapping" is wrong. I copied exact as stated under README.md (xxxx for sure changed)

sensor:
    - platform: fusion_solar_kiosk
    kiosks:
        - id: "XXXXX"
        name: "A readable name for the plant"

What am I doing wrong? Can someone give me a short hint please?

Many thanks

**Comment by nickfysiek** [comment]
I am having the exact same problem! If anyone could help

**Comment by nickfysiek** [comment]
This one worked for me!

sensor:
    - platform: fusion_solar_kiosk
      kiosks:
        - id: XXXX
          name: "zonnepanelen"

**Comment by AndreB81** [comment]
Sorry for coming back so late but unfortunately the problem still exists.

**Comment by Pme1159** [comment]
Hello, I have a similar problem than AndreB81.
This configuration is accepted by File Editor : 
sensor:
  - platform: fusion_solar_kiosk
    kiosks:
    - id: XXXX
    name: "SolarPlant"

But when I check the configuration before restarting I get : 
Invalid config for [sensor.fusion_solar_kiosk]: extra keys not allowed @ data['name']. Got 'SolarPlant'
required key not provided @ data['kiosks'][0]['name']. Got None. (See ?, line ?).

Thank you in advance for your support.

**Comment by AndreB81** [comment]
Many thanks Pme1159. 

You solved my issue!
