### ISSUE TITLE
Kiosk url

### ISSUE THREAD

**Issue by 3dprintingwa** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#12]
Hi there the url for my australian fusionsolar starts like this
https://sg5.fusionsolar.huawei.com instead of ...eu5....

Is it possible to configure this?
Many thanks

**Comment by Unifex4** [comment]
Hi,
I'm also in WA and managed to get it working :) 
Use the editor on the "sensor.py" file and change "eu5" to "sg5" on line 36.
File & Path to edit:- /config/custom_components/fusion_solar_kiosk/sensor.py
Line 36 after edit:-         api = FusionSolarKioksApi('https://eu5.fusionsolar.huawei.com')
Line 36 after edit:-         api = FusionSolarKioksApi('https://sg5.fusionsolar.huawei.com')

Hope that helps.
Cheers,
Unifex

**Comment by 3dprintingwa** [comment]
Hi
all working now after editing the file the way you mentioned
Thanks for your help
