### ISSUE TITLE
config validation invalid

### ISSUE THREAD

**Issue by Palpyroth** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#15]
Hello,
I'm new in HA, I've followed the redme.md and when I want to past the code into configuration.yaml, I've some indentation error.
If I listen the compilator, the indentation bellow is OK
```
sensor:
- platform: fusion_solar_kiosk
kiosks:
- id: "MY_CORRECT_INFO"
name: "test"
```

But when I check the config, I've these errors:
```
Integration error: name - Integration 'name' not found.
Integration error: kiosks - Integration 'kiosks' not found.
Invalid config for [sensor.fusion_solar_kiosk]: required key not provided @ data['kiosks']. Got None. (See ?, line ?). 

```
Can you help me to understand?

Thnak you

**Comment by MicheleMercuri** [comment]
should be

sensor:
  - platform: fusion_solar_kiosk
    kiosks:
      id: "XXXXXX"
      name: "A readable name for the plant"

**Comment by Palpyroth** [comment]
with this syntax 

```
Invalid config for [sensor.fusion_solar_kiosk]: required key not provided @ data['kiosks']. Got None. (See ?, line ?). 
Integration error: kiosks - Integration 'kiosks' not found.
```

I'm gonna crazy

**Comment by varn-lt** [comment]
you both are wrong, here spaces are very important, and the correct code example is here in this post:
https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk/issues/14#issuecomment-1010777203

**Comment by tijsverkoyen** [comment]
As @varn-lt correctly states: the spaces are very important
