### ISSUE TITLE
Kiosk mode button missing on site.

### ISSUE THREAD

**Issue by HenkSiemer** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#18]
Hi,
 is it just me or did the kiosk button dissappear from the fusion solar site?
now i cant get the correct url.

**Comment by tijsverkoyen** [comment]
@HenkSiemer probably you are an admin? In that case you need to create a user. If you are not, you probably should click on the plant first.

1. Sign in on the Huawei FusionSolar portal: https://eu5.fusionsolar.huawei.com/.
2. Select your plant if needed.
3. At the top there is a button: "Kiosk", click it.
4. An overlay will open, and you need to enable the kiosk view by enabling the toggle.
5. Note down the url that is shown.

<img width="667" alt="kiosk" src="https://user-images.githubusercontent.com/250042/151317469-c1532458-38f7-427f-a2fc-a8257818ab3f.png">

**Comment by MathiasDeWeerdt** [comment]
@tijsverkoyen 

I have 3 users.
- Installer
- Owner 
- Guest

None of these can see the kiosk button. 
Any ideas?

**Comment by MathiasDeWeerdt** [comment]
It was missing in chrome. Worked fine with firefox. Seems that chrome isnt rendering the button correctly most of the time.
