### ISSUE TITLE
Use FusionSolar REST api instead of Kiosk mode

### ISSUE THREAD

**Issue by inigoml** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#19]
Hi @tijsverkoyen 

Until last firmware upgrade, I was using huawei_solar integration from emilv2 in order to obtain quality info from my Huawei Solar inverter. Unfortunately, Huawei has deprecated modtbus direct access in SUN2000L inverter series and now I have to downgrade firmware. Probably, in a few some upgrades they will remove access to FusionSolar for older firmware version like they did in December and so it's just a matter of time until we loose rich inverter monitoring.

I've been looking at your integration and I thing that instead of using Kiosk mode, we could use Fusionsolar API. This API give us plenty more information about inverter status and is used by FusionSolar portal. I'm not programmer although I'm able to modify code programmed by others, but in this case it's out of my skills.

There is also a FusionSolar API already documented (more or less)

By inspecting Fusionsolar web, we can obtain plenty data from our inverters like daily performance:
![image](https://user-images.githubusercontent.com/7486708/151040310-5b1edaed-5dff-442d-98bc-52620425cbb8.png)

Energy flow:
![image](https://user-images.githubusercontent.com/7486708/151040457-fa038b93-04a9-4fed-9c4a-5f779dbdf416.png)

Or realtime information:
![image](https://user-images.githubusercontent.com/7486708/151040673-12f54951-4112-4a70-837b-7738889d766a.png)

**Comment by tijsverkoyen** [comment]
At this point I have no intention to switch to the FusionSolar REST API. To be able to use the FusionSolar API you have to do a lot os steps, including contacting the service team to obtain an openAPI account. Which is not something most users will be able to understand/do.
