### ISSUE TITLE
cannot import name 'STATE_CLASS_TOTAL_INCREASING' 

### ISSUE THREAD

**Issue by tellblom** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#8]
I get the following error after configuring the KIOSK id 

Any Ideas?

Running HA Core 2021.2.3

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 8:39:22 (1 occurrences)
Last logged: 8:39:22

Platform error sensor.fusion_solar_kiosk - cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

**Comment by Zolli** [comment]
Your HA installation is really old, you need to update at least 2021.8.
